### ISSUE TITLE
where to download the ford dataset?

### ISSUE THREAD

**Issue by xiaoshou-zheng** [InterDigitalInc/GRASP-Net#1]
Hello! 
I would like to train this model. Do you have any suggestions on where I can download the Ford dataset? 
Thank you very much!

**Comment by wu5chengwei** [comment]
> Hello! I would like to train this model. Do you have any suggestions on where I can download the Ford dataset? Thank you very much!

Hi, do you find these dataset?

**Comment by jpangidcc** [comment]
Hi @xiaoshou-zheng and @wu5chengwei, the Ford sequences are a dataset used in the MPEG community for a long time. However, it is not publically available and the amount of data is limited. In fact, the Ford sequences have very similar characteristics to the KITTI datasets and are both acquired by the Velodyne LiDAR. Thus, you may use the KITTI dataset instead. When using the KITTI dataset, you can quantize them to 18-bit (ranging from [0, 2^18-1]) by: (1) simply dividing the floating-point values by 0.001 followed by rounding to the nearest integer value, then (2) adding 131072 to each dimension (x, y, z).
