### ISSUE TITLE
where to get the dataset

### ISSUE THREAD

**Issue by HarmonyZeno** [InterDigitalInc/GRASP-Net#2]
Hello InterDigitallInc,

Firstly, I want to express my gratitude for your excellent work on GRASO-Net. I found it very insightful and it has been a valuable resource for my research.

However, I am struggling to find access to the dataset used in your project. I have been unable to locate it in the repository and there doesn't seem to be a link or reference to it in the documentation.

Could you kindly provide guidance on how I might obtain the dataset? If it's not available publicly, would you be able to share the process or methodology to generate a similar dataset?

Thank you in advance for your time and assistance. I look forward to continuing to learn from your work on GRASO-Net.

Best regards,
A Student Majored AI

**Comment by jpangidcc** [comment]
@zzltly Hi I am the first author of GRASP-Net, thanks for raising up this question. I have just come across it. Actually, all the point clouds tested in our work come from the MPEG Common Test Conditions (CTC) and are available via the internal server of MPEG. I am not sure how to grab all of these point clouds in public domains. However, some of them is available via [here](http://plenodb.jpeg.org/pc/8ilabs/). And seems that this [repo](https://github.com/mauriceqch/pcc_geo_cnn_v2) also holds some of them.

**Comment by HarmonyZeno** [comment]
Thanks a lot!
